each [msfp_start_hour],each [msfp_start_hour] - #duration(0,0,0,Time.Second([msfp_start_hour]))
= Table.ReplaceValue(#"Columnas con nombre cambiado1",each [Hora de invitaci贸n],each [Hora de invitaci贸n] - #duration(0,0,0,Time.Second([Hora de invitaci贸n])),Replacer.ReplaceValue,{"Hora de invitaci贸n"})
